#!/bin/bash
. /.denv
set -x
if [[ "$FRPS" == 1 ]]; then
  echo "frps enabled, start frps"
  exec frps -c /etc/frp/frps.ini
else
  echo "frps not enabled, frps down"
  sv down frps
  exec sleep infinity
fi
