#!/bin/bash
. /.denv
mkdir -p ~/.ssh
mkdir -p /git_sync_dir
printf -- "${GIT_SSH_KEY}" > ~/.ssh/id_rsa
chmod -R 700 ~/.ssh
ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

git config --global user.email $GIT_EMAIL
git config --global user.name $GIT_NAME

if [ -z "$(ls -A /git_sync_dir)" ]; then
    git clone $GIT_REPO_URL /git_sync_dir
elif [[ ! -e /git_sync_dir/.git ]]; then
    git clone $GIT_REPO_URL /git_temp
    mv /git_temp/.git /git_sync_dir
fi

cd /git_sync_dir
git pull -s recursive -X ours
git add -A
git commit -m "$(date)"
git push

sleep $GIT_SYNC_INTERVAL
