#!/bin/bash
set -e
function get_cpu_architecture()
{
    local cpuarch=$(uname -m)
    case $cpuarch in
         x86_64)
              echo "amd64";
              ;;
         aarch64)
              echo "arm64";
              ;;
         *)
              echo "Not supported cpu architecture: ${cpuarch}"  >&2
              exit 1
              ;;
    esac
}
export cpu_arch=$(get_cpu_architecture)
export > /.denv
export LD_PRELOAD=/lib/runit-docker.so
source /etc/profile
exec runsvdir /etc/service
